import { useRouter } from "next/router";
import { useEffect } from "react";
// # Main

// [[index]]

// [//begin]: # "Autogenerated link references for markdown compatibility"
// [index]: en/index "Index"
// [//end]: # "Autogenerated link references"

export default function index() {
  const router = useRouter();
  useEffect(() => {
    router.push("/en/home_en");
  }, []);
  return <div>pepe</div>;
}
